name: Continuous Integration

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    name: Build and Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2 

      - name: Setup Java JDK 17
        uses: actions/setup-java@v4.4.0 
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle Environment
        uses: gradle/actions/setup-gradle@v4

      - name: Compile and Execute Tests
        # Executa o wrapper explicitamente apontando para a subpasta do Java
        run: |
          chmod +x ./checking-account-operation/gradlew
          ./checking-account-operation/gradlew test -p checking-account-operation -Dspring.kafka.listener.auto-startup=false --info
