name: SonarQube Analysis

on:
  push:
    branches:
      - main
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonar:
    name: Build and Analyze
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # O Gradle do seu projeto roda com Java 24 sem quebrar os limites de compatibilidade das ferramentas
      - name: Set up JDK 24 for Gradle
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'
          cache: gradle

      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Remove local Windows Java Home
        run: |
          if [ -f gradle.properties ]; then
            echo "Limpando configuracoes locais de Java Home do Windows..."
            sed -i '/org.gradle.java.home/d' gradle.properties
          fi

      # Permite que o Gradle baixe o JDK 25 de forma isolada para compilar seu código usando o Toolchain
      - name: Enable Gradle Toolchain Auto-Provisioning
        run: |
          mkdir -p ~/.gradle
          echo "org.gradle.java.installations.auto-download=true" >> ~/.gradle/gradle.properties

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          ./gradlew build sonar \
            -Dsonar.projectKey=heitorseemann_checking-account-operation \
            -Dsonar.organization=heitorseemann \
            -Dsonar.host.url=https://sonarcloud.io
